### PR TITLE
Fix cmpfind to allow single character search

### LINKED ISSUE #317: [PE-D][Tester B] `cmpfind` rejects valid one-character substring searches
## Description
- The User Guide describes company search as substring matching. 
- The parser validates each keyword as a full CompanyName, which requires at least two characters, however, they allow adding in of company with keywords that is one letter. 
- This cause the common substring searches for company with names only 1 letter to be rejected.

## Steps to reproduce
1. `clear`
2. `cmpadd /c X Corp /d Elon Musk Company`
3. `cmpfind X`: will have error and the except thrown to the user is that keyword provided is not a valid company name. 

## Screenshot
1. Adding a company with naming like `X Corp`:
Image

Image

2. When searching substring for `Xcorp` will return error.

Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by niclzy**
Fix https://github.com/AY2526S2-CS2103T-W11-2/tp/issues/317

Allows single character search, while the single character still obeys the `Company.name`'s REGEX (no `/`, `\`, `@` etc)

### CODE REVIEW

**Review by Egg-Fish — APPROVED** [review]
LGTM

File: src/main/java/hitlist/logic/parser/FindCompanyCommandParser.java [hunk 1]
```diff
@@ -9,13 +9,17 @@
...
 
 /**
  * Parses input arguments and creates a new FindCompanyCommand object
  */
 public class FindCompanyCommandParser implements Parser<FindCompanyCommand> {
 
+    /**
+     * The search string should only consist of the characters defined below, and should not be blank.
+     */
+    public static final String VALIDATION_REGEX = "^[^\\s/][^/\\v]*$";
```
Comment (C4RR0T02) [inline src/main/java/hitlist/logic/parser/FindCompanyCommandParser.java]:
```suggestion
    public static final String VALIDATION_REGEX = "^[^/\s\p{C}][^/\v\p{C}]*$";
```
Attempts to block any whitespace zero width character

**Review by C4RR0T02 — CHANGES_REQUESTED** [review]
Change this regex

**Review by C4RR0T02 — APPROVED** [review]
LGTM
