### PR TITLE
Fix case-insensitive name deduplication for grpadd

### LINKED ISSUE #265: [PE-D][Tester B] User behavior for `grpadd` is not handled on duplicate member names with different casing
## Description 
When `grpadd` commands receives arguments with the same name but different casing (e.g., `/n Alice /n alice`), HitList just stucked there and users are unable to enter the command. 

## Expected behavior
The system should consistently treat names as case-insensitive during the grpadd process. It should either:
1. Automatically deduplicate the names before processing.
2. Display a validation error message to the user 

To ensure that no more than one contact with the same name (regardless of casing) can be added to the group.

## Actual behavior
No error message. 

## Step to reproduce
0. `clear`: Clear HitList
1. `add /n Alice /p 111` : Add a contact for Alice
2. `grpadd /g Team /n Alice /n alice` --> Observe that legitimate user behavior is not handled

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by Leiruz**
Fixes #265

## Summary

* fix `Name.hashCode()` so it is consistent with case-insensitive `Name.equals()`
* add regression tests for case-insensitive equality and hash code behavior
* restore correct deduplication of repeated member names such as `/n Alice /n alice` during `grpadd`

## Root cause

`grpadd` parses member names into a `Set<Name>`.
`Name.equals()` already compares names case-insensitively, but `Name.hashCode()` previously used the original casing.
That violated the `equals`/`hashCode` contract and allowed hash-based collections to treat `Alice` and `alice` as different entries.

## Testing

* `./gradlew test`
* `./gradlew check coverage`
* manual test: `grpadd /g Team /n Alice /n alice`

### CODE REVIEW

File: src/main/java/hitlist/model/person/Name.java [hunk 1]
```diff
@@ -11,7 +13,7 @@ public class Name {
 
     public static final String MESSAGE_CONSTRAINTS =
             "Names should only contain alphabetic characters, dashes,"
-            + " apostrophes, and spaces, and it should not be blank";
+                    + " apostrophes, and spaces, and it should not be blank";
```
Comment (niclzy) [inline src/main/java/hitlist/model/person/Name.java]: Consider proper indentation

**Review by niclzy — CHANGES_REQUESTED** [review]

File: src/main/java/hitlist/model/person/Name.java (hunk 1 above)
Comment (Leiruz) [reply src/main/java/hitlist/model/person/Name.java]: okay updated

**Review by niclzy — APPROVED** [review]
lgtm
