### PR TITLE
Use CommandException when company DNE

### LINKED ISSUE #159: Invalid company in roleadd command fails without error message
The red error message is not shown when the company name is invalid.
Image

Image

Image

### PR DESCRIPTION
**Pull request by lukeetann**
Fixes #159

### CODE REVIEW

File: src/test/java/hitlist/logic/commands/AddCompanyRoleCommandTest.java [hunk 1]
```diff
@@ -49,7 +50,9 @@ public void execute_roleAcceptedByModel_addSuccessful() throws Exception {
                 .withName("Valid Role Name")
                 .withDescription("Valid Role Description")
                 .build();
-        CompanyName companyName = new CompanyBuilder().withName(VALID_COMPANY_NAME_GOOGLE).build().getName();
+        Company Google = new CompanyBuilder().withName(VALID_COMPANY_NAME_GOOGLE).build();
```
Comment (Egg-Fish) [inline src/test/java/hitlist/logic/commands/AddCompanyRoleCommandTest.java]: This should be lowercase `Company google = ...`, as per coding standards

File: src/test/java/hitlist/logic/commands/AddCompanyRoleCommandTest.java [hunk 2]
```diff
@@ -68,7 +71,8 @@ public void execute_duplicateCompanyRole_throwsCommandException() {
...
```
Comment (Egg-Fish) [inline src/test/java/hitlist/logic/commands/AddCompanyRoleCommandTest.java]: This should be lowercase `Company google = ...`, as per coding standards
